
# This file is automatically generated, you probably don't want to edit this

barOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "categorical",
            catvar = NULL,
            convar = NULL,
            counts = NULL,
            congroup = NULL,
            countsLabels = NULL,
            flipAxes = FALSE,
            width = 500,
            height = 500,
            se = FALSE,
            title = "",
            titleAlign = "center",
            subtitle = "",
            subtitleAlign = "left",
            caption = "",
            captionAlign = "right",
            xLabel = "",
            xLabelAlign = "center",
            yLabel = "",
            yLabelAlign = "center", ...) {

            super$initialize(
                package="jmvplot",
                name="bar",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "categorical",
                    "continuous",
                    "counts"),
                default="categorical")
            private$..catvar <- jmvcore::OptionVariable$new(
                "catvar",
                catvar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..convar <- jmvcore::OptionVariable$new(
                "convar",
                convar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..congroup <- jmvcore::OptionVariable$new(
                "congroup",
                congroup,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..countsLabels <- jmvcore::OptionVariable$new(
                "countsLabels",
                countsLabels,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..flipAxes <- jmvcore::OptionBool$new(
                "flipAxes",
                flipAxes,
                default=FALSE)
            private$..width <- jmvcore::OptionNumber$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionNumber$new(
                "height",
                height,
                default=500)
            private$..se <- jmvcore::OptionBool$new(
                "se",
                se,
                default=FALSE)
            private$..title <- jmvcore::OptionString$new(
                "title",
                title,
                default="")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..subtitle <- jmvcore::OptionString$new(
                "subtitle",
                subtitle,
                default="")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="left")
            private$..caption <- jmvcore::OptionString$new(
                "caption",
                caption,
                default="")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="right")
            private$..xLabel <- jmvcore::OptionString$new(
                "xLabel",
                xLabel,
                default="")
            private$..xLabelAlign <- jmvcore::OptionList$new(
                "xLabelAlign",
                xLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..yLabel <- jmvcore::OptionString$new(
                "yLabel",
                yLabel,
                default="")
            private$..yLabelAlign <- jmvcore::OptionList$new(
                "yLabelAlign",
                yLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")

            self$.addOption(private$..mode)
            self$.addOption(private$..catvar)
            self$.addOption(private$..convar)
            self$.addOption(private$..counts)
            self$.addOption(private$..congroup)
            self$.addOption(private$..countsLabels)
            self$.addOption(private$..flipAxes)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..se)
            self$.addOption(private$..title)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..subtitle)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..caption)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..xLabel)
            self$.addOption(private$..xLabelAlign)
            self$.addOption(private$..yLabel)
            self$.addOption(private$..yLabelAlign)
        }),
    active = list(
        mode = function() private$..mode$value,
        catvar = function() private$..catvar$value,
        convar = function() private$..convar$value,
        counts = function() private$..counts$value,
        congroup = function() private$..congroup$value,
        countsLabels = function() private$..countsLabels$value,
        flipAxes = function() private$..flipAxes$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        se = function() private$..se$value,
        title = function() private$..title$value,
        titleAlign = function() private$..titleAlign$value,
        subtitle = function() private$..subtitle$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        caption = function() private$..caption$value,
        captionAlign = function() private$..captionAlign$value,
        xLabel = function() private$..xLabel$value,
        xLabelAlign = function() private$..xLabelAlign$value,
        yLabel = function() private$..yLabel$value,
        yLabelAlign = function() private$..yLabelAlign$value),
    private = list(
        ..mode = NA,
        ..catvar = NA,
        ..convar = NA,
        ..counts = NA,
        ..congroup = NA,
        ..countsLabels = NA,
        ..flipAxes = NA,
        ..width = NA,
        ..height = NA,
        ..se = NA,
        ..title = NA,
        ..titleAlign = NA,
        ..subtitle = NA,
        ..subtitleAlign = NA,
        ..caption = NA,
        ..captionAlign = NA,
        ..xLabel = NA,
        ..xLabelAlign = NA,
        ..yLabel = NA,
        ..yLabelAlign = NA)
)

barResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Barplot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=500,
                height=500,
                renderFun=".barPlot"))}))

barBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvplot",
                name = "bar",
                version = c(1,0,0),
                options = options,
                results = barResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Barplot
#'
#' 
#' @param mode .
#' @param data .
#' @param catvar .
#' @param convar .
#' @param counts .
#' @param congroup .
#' @param countsLabels .
#' @param flipAxes .
#' @param width .
#' @param height .
#' @param se .
#' @param title .
#' @param titleAlign .
#' @param subtitle .
#' @param subtitleAlign .
#' @param caption .
#' @param captionAlign .
#' @param xLabel .
#' @param xLabelAlign .
#' @param yLabel .
#' @param yLabelAlign .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image containing the bar plot \cr
#' }
#'
#' @export
bar <- function(
    mode = "categorical",
    data,
    catvar,
    convar,
    counts,
    congroup,
    countsLabels,
    flipAxes = FALSE,
    width = 500,
    height = 500,
    se = FALSE,
    title = "",
    titleAlign = "center",
    subtitle = "",
    subtitleAlign = "left",
    caption = "",
    captionAlign = "right",
    xLabel = "",
    xLabelAlign = "center",
    yLabel = "",
    yLabelAlign = "center") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bar requires jmvcore to be installed (restart may be required)")

    if ( ! missing(catvar)) catvar <- jmvcore::resolveQuo(jmvcore::enquo(catvar))
    if ( ! missing(convar)) convar <- jmvcore::resolveQuo(jmvcore::enquo(convar))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if ( ! missing(congroup)) congroup <- jmvcore::resolveQuo(jmvcore::enquo(congroup))
    if ( ! missing(countsLabels)) countsLabels <- jmvcore::resolveQuo(jmvcore::enquo(countsLabels))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(catvar), catvar, NULL),
            `if`( ! missing(convar), convar, NULL),
            `if`( ! missing(counts), counts, NULL),
            `if`( ! missing(congroup), congroup, NULL),
            `if`( ! missing(countsLabels), countsLabels, NULL))

    for (v in catvar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in congroup) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in countsLabels) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- barOptions$new(
        mode = mode,
        catvar = catvar,
        convar = convar,
        counts = counts,
        congroup = congroup,
        countsLabels = countsLabels,
        flipAxes = flipAxes,
        width = width,
        height = height,
        se = se,
        title = title,
        titleAlign = titleAlign,
        subtitle = subtitle,
        subtitleAlign = subtitleAlign,
        caption = caption,
        captionAlign = captionAlign,
        xLabel = xLabel,
        xLabelAlign = xLabelAlign,
        yLabel = yLabel,
        yLabelAlign = yLabelAlign)

    analysis <- barClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

