
# This file is automatically generated, you probably don't want to edit this

barOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "categorical",
            catvar = NULL,
            convar = NULL,
            counts = NULL,
            congroup = NULL,
            countsLabels = NULL,
            flipAxes = FALSE,
            barWidth = 0.9,
            width = 500,
            height = 500,
            errorBars = NULL,
            ciWidth = 0.95,
            title = "",
            titleAlign = "center",
            titleFontSize = 16,
            subtitle = "",
            subtitleAlign = "left",
            subtitleFontSize = 16,
            caption = "",
            captionAlign = "right",
            captionFontSize = 12,
            xLabel = "",
            xLabelAlign = "center",
            xLabelFontSize = 16,
            yLabel = "",
            yLabelAlign = "center",
            yLabelFontSize = 16,
            titleType = "title",
            yAxisLabelFontSize = 12,
            yAxisRangeType = NULL,
            yAxisRangeMin = NULL,
            yAxisRangeMax = NULL,
            xAxisLabelFontSize = 12,
            xAxisLabelFontSizeRevLabels = FALSE, ...) {

            super$initialize(
                package="jmvplot",
                name="bar",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "categorical",
                    "continuous",
                    "counts"),
                default="categorical")
            private$..catvar <- jmvcore::OptionVariable$new(
                "catvar",
                catvar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..convar <- jmvcore::OptionVariable$new(
                "convar",
                convar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..congroup <- jmvcore::OptionVariable$new(
                "congroup",
                congroup,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..countsLabels <- jmvcore::OptionVariable$new(
                "countsLabels",
                countsLabels,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..flipAxes <- jmvcore::OptionBool$new(
                "flipAxes",
                flipAxes,
                default=FALSE)
            private$..barWidth <- jmvcore::OptionNumber$new(
                "barWidth",
                barWidth,
                default=0.9,
                min=0,
                max=1)
            private$..width <- jmvcore::OptionNumber$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionNumber$new(
                "height",
                height,
                default=500)
            private$..errorBars <- jmvcore::OptionList$new(
                "errorBars",
                errorBars,
                options=list(
                    "none",
                    "sd",
                    "se",
                    "ci"))
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=0.95,
                min=0,
                max=1)
            private$..title <- jmvcore::OptionString$new(
                "title",
                title,
                default="")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..titleFontSize <- jmvcore::OptionNumber$new(
                "titleFontSize",
                titleFontSize,
                default=16)
            private$..subtitle <- jmvcore::OptionString$new(
                "subtitle",
                subtitle,
                default="")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="left")
            private$..subtitleFontSize <- jmvcore::OptionNumber$new(
                "subtitleFontSize",
                subtitleFontSize,
                default=16)
            private$..caption <- jmvcore::OptionString$new(
                "caption",
                caption,
                default="")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="right")
            private$..captionFontSize <- jmvcore::OptionNumber$new(
                "captionFontSize",
                captionFontSize,
                default=12)
            private$..xLabel <- jmvcore::OptionString$new(
                "xLabel",
                xLabel,
                default="")
            private$..xLabelAlign <- jmvcore::OptionList$new(
                "xLabelAlign",
                xLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..xLabelFontSize <- jmvcore::OptionNumber$new(
                "xLabelFontSize",
                xLabelFontSize,
                default=16)
            private$..yLabel <- jmvcore::OptionString$new(
                "yLabel",
                yLabel,
                default="")
            private$..yLabelAlign <- jmvcore::OptionList$new(
                "yLabelAlign",
                yLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..yLabelFontSize <- jmvcore::OptionNumber$new(
                "yLabelFontSize",
                yLabelFontSize,
                default=16)
            private$..titleType <- jmvcore::OptionList$new(
                "titleType",
                titleType,
                options=list(
                    "title",
                    "subtitle",
                    "caption",
                    "xTitle",
                    "yTitle"),
                default="title")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"))
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelFontSizeRevLabels <- jmvcore::OptionBool$new(
                "xAxisLabelFontSizeRevLabels",
                xAxisLabelFontSizeRevLabels,
                default=FALSE)

            self$.addOption(private$..mode)
            self$.addOption(private$..catvar)
            self$.addOption(private$..convar)
            self$.addOption(private$..counts)
            self$.addOption(private$..congroup)
            self$.addOption(private$..countsLabels)
            self$.addOption(private$..flipAxes)
            self$.addOption(private$..barWidth)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..errorBars)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..title)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..subtitle)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..caption)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..xLabel)
            self$.addOption(private$..xLabelAlign)
            self$.addOption(private$..xLabelFontSize)
            self$.addOption(private$..yLabel)
            self$.addOption(private$..yLabelAlign)
            self$.addOption(private$..yLabelFontSize)
            self$.addOption(private$..titleType)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelFontSizeRevLabels)
        }),
    active = list(
        mode = function() private$..mode$value,
        catvar = function() private$..catvar$value,
        convar = function() private$..convar$value,
        counts = function() private$..counts$value,
        congroup = function() private$..congroup$value,
        countsLabels = function() private$..countsLabels$value,
        flipAxes = function() private$..flipAxes$value,
        barWidth = function() private$..barWidth$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        errorBars = function() private$..errorBars$value,
        ciWidth = function() private$..ciWidth$value,
        title = function() private$..title$value,
        titleAlign = function() private$..titleAlign$value,
        titleFontSize = function() private$..titleFontSize$value,
        subtitle = function() private$..subtitle$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        caption = function() private$..caption$value,
        captionAlign = function() private$..captionAlign$value,
        captionFontSize = function() private$..captionFontSize$value,
        xLabel = function() private$..xLabel$value,
        xLabelAlign = function() private$..xLabelAlign$value,
        xLabelFontSize = function() private$..xLabelFontSize$value,
        yLabel = function() private$..yLabel$value,
        yLabelAlign = function() private$..yLabelAlign$value,
        yLabelFontSize = function() private$..yLabelFontSize$value,
        titleType = function() private$..titleType$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelFontSizeRevLabels = function() private$..xAxisLabelFontSizeRevLabels$value),
    private = list(
        ..mode = NA,
        ..catvar = NA,
        ..convar = NA,
        ..counts = NA,
        ..congroup = NA,
        ..countsLabels = NA,
        ..flipAxes = NA,
        ..barWidth = NA,
        ..width = NA,
        ..height = NA,
        ..errorBars = NA,
        ..ciWidth = NA,
        ..title = NA,
        ..titleAlign = NA,
        ..titleFontSize = NA,
        ..subtitle = NA,
        ..subtitleAlign = NA,
        ..subtitleFontSize = NA,
        ..caption = NA,
        ..captionAlign = NA,
        ..captionFontSize = NA,
        ..xLabel = NA,
        ..xLabelAlign = NA,
        ..xLabelFontSize = NA,
        ..yLabel = NA,
        ..yLabelAlign = NA,
        ..yLabelFontSize = NA,
        ..titleType = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelFontSizeRevLabels = NA)
)

barResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Barplot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=500,
                height=500,
                renderFun=".barPlot"))}))

barBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvplot",
                name = "bar",
                version = c(1,0,0),
                options = options,
                results = barResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Barplot
#'
#' 
#' @param mode .
#' @param data .
#' @param catvar .
#' @param convar .
#' @param counts .
#' @param congroup .
#' @param countsLabels .
#' @param flipAxes .
#' @param barWidth .
#' @param width .
#' @param height .
#' @param errorBars .
#' @param ciWidth .
#' @param title .
#' @param titleAlign .
#' @param titleFontSize .
#' @param subtitle .
#' @param subtitleAlign .
#' @param subtitleFontSize .
#' @param caption .
#' @param captionAlign .
#' @param captionFontSize .
#' @param xLabel .
#' @param xLabelAlign .
#' @param xLabelFontSize .
#' @param yLabel .
#' @param yLabelAlign .
#' @param yLabelFontSize .
#' @param titleType .
#' @param yAxisLabelFontSize .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelFontSizeRevLabels .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image containing the bar plot \cr
#' }
#'
#' @export
bar <- function(
    mode = "categorical",
    data,
    catvar,
    convar,
    counts,
    congroup,
    countsLabels,
    flipAxes = FALSE,
    barWidth = 0.9,
    width = 500,
    height = 500,
    errorBars,
    ciWidth = 0.95,
    title = "",
    titleAlign = "center",
    titleFontSize = 16,
    subtitle = "",
    subtitleAlign = "left",
    subtitleFontSize = 16,
    caption = "",
    captionAlign = "right",
    captionFontSize = 12,
    xLabel = "",
    xLabelAlign = "center",
    xLabelFontSize = 16,
    yLabel = "",
    yLabelAlign = "center",
    yLabelFontSize = 16,
    titleType = "title",
    yAxisLabelFontSize = 12,
    yAxisRangeType,
    yAxisRangeMin,
    yAxisRangeMax,
    xAxisLabelFontSize = 12,
    xAxisLabelFontSizeRevLabels = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bar requires jmvcore to be installed (restart may be required)")

    if ( ! missing(catvar)) catvar <- jmvcore::resolveQuo(jmvcore::enquo(catvar))
    if ( ! missing(convar)) convar <- jmvcore::resolveQuo(jmvcore::enquo(convar))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if ( ! missing(congroup)) congroup <- jmvcore::resolveQuo(jmvcore::enquo(congroup))
    if ( ! missing(countsLabels)) countsLabels <- jmvcore::resolveQuo(jmvcore::enquo(countsLabels))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(catvar), catvar, NULL),
            `if`( ! missing(convar), convar, NULL),
            `if`( ! missing(counts), counts, NULL),
            `if`( ! missing(congroup), congroup, NULL),
            `if`( ! missing(countsLabels), countsLabels, NULL))

    for (v in catvar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in congroup) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in countsLabels) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- barOptions$new(
        mode = mode,
        catvar = catvar,
        convar = convar,
        counts = counts,
        congroup = congroup,
        countsLabels = countsLabels,
        flipAxes = flipAxes,
        barWidth = barWidth,
        width = width,
        height = height,
        errorBars = errorBars,
        ciWidth = ciWidth,
        title = title,
        titleAlign = titleAlign,
        titleFontSize = titleFontSize,
        subtitle = subtitle,
        subtitleAlign = subtitleAlign,
        subtitleFontSize = subtitleFontSize,
        caption = caption,
        captionAlign = captionAlign,
        captionFontSize = captionFontSize,
        xLabel = xLabel,
        xLabelAlign = xLabelAlign,
        xLabelFontSize = xLabelFontSize,
        yLabel = yLabel,
        yLabelAlign = yLabelAlign,
        yLabelFontSize = yLabelFontSize,
        titleType = titleType,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelFontSizeRevLabels = xAxisLabelFontSizeRevLabels)

    analysis <- barClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

