
# This file is automatically generated, you probably don't want to edit this

boxOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            group = NULL,
            flipAxes = FALSE,
            notch = FALSE,
            width = 500,
            height = 500,
            title = "",
            titleAlign = "center",
            titleFontSize = 16,
            subtitle = "",
            subtitleAlign = "left",
            subtitleFontSize = 16,
            caption = "",
            captionAlign = "right",
            captionFontSize = 12,
            xLabel = "",
            xLabelAlign = "center",
            xLabelFontSize = 16,
            yLabel = "",
            yLabelAlign = "center",
            yLabelFontSize = 16,
            titleType = "title",
            yAxisLabelFontSize = 12,
            yAxisRangeType = NULL,
            yAxisRangeMin = NULL,
            yAxisRangeMax = NULL,
            xAxisLabelFontSize = 12,
            xAxisLabelFontSizeRevLabels = FALSE, ...) {

            super$initialize(
                package="jmvplot",
                name="box",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..flipAxes <- jmvcore::OptionBool$new(
                "flipAxes",
                flipAxes,
                default=FALSE)
            private$..notch <- jmvcore::OptionBool$new(
                "notch",
                notch,
                default=FALSE)
            private$..width <- jmvcore::OptionNumber$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionNumber$new(
                "height",
                height,
                default=500)
            private$..title <- jmvcore::OptionString$new(
                "title",
                title,
                default="")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..titleFontSize <- jmvcore::OptionNumber$new(
                "titleFontSize",
                titleFontSize,
                default=16)
            private$..subtitle <- jmvcore::OptionString$new(
                "subtitle",
                subtitle,
                default="")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="left")
            private$..subtitleFontSize <- jmvcore::OptionNumber$new(
                "subtitleFontSize",
                subtitleFontSize,
                default=16)
            private$..caption <- jmvcore::OptionString$new(
                "caption",
                caption,
                default="")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="right")
            private$..captionFontSize <- jmvcore::OptionNumber$new(
                "captionFontSize",
                captionFontSize,
                default=12)
            private$..xLabel <- jmvcore::OptionString$new(
                "xLabel",
                xLabel,
                default="")
            private$..xLabelAlign <- jmvcore::OptionList$new(
                "xLabelAlign",
                xLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..xLabelFontSize <- jmvcore::OptionNumber$new(
                "xLabelFontSize",
                xLabelFontSize,
                default=16)
            private$..yLabel <- jmvcore::OptionString$new(
                "yLabel",
                yLabel,
                default="")
            private$..yLabelAlign <- jmvcore::OptionList$new(
                "yLabelAlign",
                yLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..yLabelFontSize <- jmvcore::OptionNumber$new(
                "yLabelFontSize",
                yLabelFontSize,
                default=16)
            private$..titleType <- jmvcore::OptionList$new(
                "titleType",
                titleType,
                options=list(
                    "title",
                    "subtitle",
                    "caption",
                    "xTitle",
                    "yTitle"),
                default="title")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"))
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelFontSizeRevLabels <- jmvcore::OptionBool$new(
                "xAxisLabelFontSizeRevLabels",
                xAxisLabelFontSizeRevLabels,
                default=FALSE)

            self$.addOption(private$..var)
            self$.addOption(private$..group)
            self$.addOption(private$..flipAxes)
            self$.addOption(private$..notch)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..title)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..subtitle)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..caption)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..xLabel)
            self$.addOption(private$..xLabelAlign)
            self$.addOption(private$..xLabelFontSize)
            self$.addOption(private$..yLabel)
            self$.addOption(private$..yLabelAlign)
            self$.addOption(private$..yLabelFontSize)
            self$.addOption(private$..titleType)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelFontSizeRevLabels)
        }),
    active = list(
        var = function() private$..var$value,
        group = function() private$..group$value,
        flipAxes = function() private$..flipAxes$value,
        notch = function() private$..notch$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        title = function() private$..title$value,
        titleAlign = function() private$..titleAlign$value,
        titleFontSize = function() private$..titleFontSize$value,
        subtitle = function() private$..subtitle$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        caption = function() private$..caption$value,
        captionAlign = function() private$..captionAlign$value,
        captionFontSize = function() private$..captionFontSize$value,
        xLabel = function() private$..xLabel$value,
        xLabelAlign = function() private$..xLabelAlign$value,
        xLabelFontSize = function() private$..xLabelFontSize$value,
        yLabel = function() private$..yLabel$value,
        yLabelAlign = function() private$..yLabelAlign$value,
        yLabelFontSize = function() private$..yLabelFontSize$value,
        titleType = function() private$..titleType$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelFontSizeRevLabels = function() private$..xAxisLabelFontSizeRevLabels$value),
    private = list(
        ..var = NA,
        ..group = NA,
        ..flipAxes = NA,
        ..notch = NA,
        ..width = NA,
        ..height = NA,
        ..title = NA,
        ..titleAlign = NA,
        ..titleFontSize = NA,
        ..subtitle = NA,
        ..subtitleAlign = NA,
        ..subtitleFontSize = NA,
        ..caption = NA,
        ..captionAlign = NA,
        ..captionFontSize = NA,
        ..xLabel = NA,
        ..xLabelAlign = NA,
        ..xLabelFontSize = NA,
        ..yLabel = NA,
        ..yLabelAlign = NA,
        ..yLabelFontSize = NA,
        ..titleType = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelFontSizeRevLabels = NA)
)

boxResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Boxplot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=500,
                height=500,
                renderFun=".boxPlot"))}))

boxBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvplot",
                name = "box",
                version = c(1,0,0),
                options = options,
                results = boxResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Boxplot
#'
#' 
#' @param data .
#' @param var .
#' @param group .
#' @param flipAxes .
#' @param notch .
#' @param width .
#' @param height .
#' @param title .
#' @param titleAlign .
#' @param titleFontSize .
#' @param subtitle .
#' @param subtitleAlign .
#' @param subtitleFontSize .
#' @param caption .
#' @param captionAlign .
#' @param captionFontSize .
#' @param xLabel .
#' @param xLabelAlign .
#' @param xLabelFontSize .
#' @param yLabel .
#' @param yLabelAlign .
#' @param yLabelFontSize .
#' @param titleType .
#' @param yAxisLabelFontSize .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelFontSizeRevLabels .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image containing the box plot \cr
#' }
#'
#' @export
box <- function(
    data,
    var,
    group,
    flipAxes = FALSE,
    notch = FALSE,
    width = 500,
    height = 500,
    title = "",
    titleAlign = "center",
    titleFontSize = 16,
    subtitle = "",
    subtitleAlign = "left",
    subtitleFontSize = 16,
    caption = "",
    captionAlign = "right",
    captionFontSize = 12,
    xLabel = "",
    xLabelAlign = "center",
    xLabelFontSize = 16,
    yLabel = "",
    yLabelAlign = "center",
    yLabelFontSize = 16,
    titleType = "title",
    yAxisLabelFontSize = 12,
    yAxisRangeType,
    yAxisRangeMin,
    yAxisRangeMax,
    xAxisLabelFontSize = 12,
    xAxisLabelFontSizeRevLabels = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("box requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- boxOptions$new(
        var = var,
        group = group,
        flipAxes = flipAxes,
        notch = notch,
        width = width,
        height = height,
        title = title,
        titleAlign = titleAlign,
        titleFontSize = titleFontSize,
        subtitle = subtitle,
        subtitleAlign = subtitleAlign,
        subtitleFontSize = subtitleFontSize,
        caption = caption,
        captionAlign = captionAlign,
        captionFontSize = captionFontSize,
        xLabel = xLabel,
        xLabelAlign = xLabelAlign,
        xLabelFontSize = xLabelFontSize,
        yLabel = yLabel,
        yLabelAlign = yLabelAlign,
        yLabelFontSize = yLabelFontSize,
        titleType = titleType,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelFontSizeRevLabels = xAxisLabelFontSizeRevLabels)

    analysis <- boxClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

