
# This file is automatically generated, you probably don't want to edit this

jmvbarOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvbarOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "categorical",
            catvar = NULL,
            catgroup = NULL,
            convar = NULL,
            congroup1 = NULL,
            congroup2 = NULL,
            counts = NULL,
            countsLabels = NULL,
            countsgroup = NULL,
            flipAxes = FALSE,
            barWidth = 0.9,
            valueLabels = FALSE,
            width = 500,
            height = 500,
            errorBars = "none",
            ciWidth = 95,
            errorBarWidth = 0.1,
            errorBarSize = 0.5,
            title = "",
            titleAlign = "center",
            titleFontSize = 16,
            titleFontFace = "plain",
            subtitle = "",
            subtitleAlign = "left",
            subtitleFontSize = 16,
            subtitleFontFace = "plain",
            caption = "",
            captionAlign = "right",
            captionFontSize = 12,
            captionFontFace = "plain",
            xLabel = "",
            xLabelAlign = "center",
            xLabelFontSize = 16,
            xLabelFontFace = "plain",
            yLabel = "",
            yLabelAlign = "center",
            yLabelFontSize = 16,
            yLabelFontFace = "plain",
            titleType = "title",
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            yAxisRangeType = "auto",
            yAxisRangeMin = 0,
            yAxisRangeMax = 10,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0,
            xAxisLabelFontSizeRevLabels = FALSE,
            legendTitle = "",
            legendTitleFontSize = 16,
            legendTitleFontFace = "plain",
            legendLabelFontSize = 16,
            legendLabelFontFace = "plain",
            legendKeyWidth = 0.6,
            legendKeyHeight = 0.6,
            legenPositionType = "outside",
            legendPosition = "right",
            legendJustification = "center",
            legendPositionX = 0.8,
            legendPositionY = 0.5,
            legendDirection = "vertical",
            groupBarType = "grouped", ...) {

            super$initialize(
                package="scatr",
                name="jmvbar",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "categorical",
                    "continuous",
                    "counts"),
                default="categorical")
            private$..catvar <- jmvcore::OptionVariable$new(
                "catvar",
                catvar,
                default=NULL,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..catgroup <- jmvcore::OptionVariable$new(
                "catgroup",
                catgroup,
                default=NULL,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..convar <- jmvcore::OptionVariable$new(
                "convar",
                convar,
                default=NULL,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..congroup1 <- jmvcore::OptionVariable$new(
                "congroup1",
                congroup1,
                default=NULL,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..congroup2 <- jmvcore::OptionVariable$new(
                "congroup2",
                congroup2,
                default=NULL,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                default=NULL,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..countsLabels <- jmvcore::OptionVariable$new(
                "countsLabels",
                countsLabels,
                default=NULL,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..countsgroup <- jmvcore::OptionVariable$new(
                "countsgroup",
                countsgroup,
                default=NULL,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..flipAxes <- jmvcore::OptionBool$new(
                "flipAxes",
                flipAxes,
                default=FALSE)
            private$..barWidth <- jmvcore::OptionNumber$new(
                "barWidth",
                barWidth,
                default=0.9,
                min=0)
            private$..valueLabels <- jmvcore::OptionBool$new(
                "valueLabels",
                valueLabels,
                default=FALSE)
            private$..width <- jmvcore::OptionNumber$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionNumber$new(
                "height",
                height,
                default=500)
            private$..errorBars <- jmvcore::OptionList$new(
                "errorBars",
                errorBars,
                options=list(
                    "none",
                    "sd",
                    "se",
                    "ci"),
                default="none")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=0,
                max=100)
            private$..errorBarWidth <- jmvcore::OptionNumber$new(
                "errorBarWidth",
                errorBarWidth,
                default=0.1,
                min=0)
            private$..errorBarSize <- jmvcore::OptionNumber$new(
                "errorBarSize",
                errorBarSize,
                default=0.5,
                min=0)
            private$..title <- jmvcore::OptionString$new(
                "title",
                title,
                default="")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..titleFontSize <- jmvcore::OptionNumber$new(
                "titleFontSize",
                titleFontSize,
                default=16)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..subtitle <- jmvcore::OptionString$new(
                "subtitle",
                subtitle,
                default="")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="left")
            private$..subtitleFontSize <- jmvcore::OptionNumber$new(
                "subtitleFontSize",
                subtitleFontSize,
                default=16)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..caption <- jmvcore::OptionString$new(
                "caption",
                caption,
                default="")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="right")
            private$..captionFontSize <- jmvcore::OptionNumber$new(
                "captionFontSize",
                captionFontSize,
                default=12)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..xLabel <- jmvcore::OptionString$new(
                "xLabel",
                xLabel,
                default="")
            private$..xLabelAlign <- jmvcore::OptionList$new(
                "xLabelAlign",
                xLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..xLabelFontSize <- jmvcore::OptionNumber$new(
                "xLabelFontSize",
                xLabelFontSize,
                default=16)
            private$..xLabelFontFace <- jmvcore::OptionList$new(
                "xLabelFontFace",
                xLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..yLabel <- jmvcore::OptionString$new(
                "yLabel",
                yLabel,
                default="")
            private$..yLabelAlign <- jmvcore::OptionList$new(
                "yLabelAlign",
                yLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..yLabelFontSize <- jmvcore::OptionNumber$new(
                "yLabelFontSize",
                yLabelFontSize,
                default=16)
            private$..yLabelFontFace <- jmvcore::OptionList$new(
                "yLabelFontFace",
                yLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..titleType <- jmvcore::OptionList$new(
                "titleType",
                titleType,
                options=list(
                    "title",
                    "subtitle",
                    "caption",
                    "xTitle",
                    "yTitle"),
                default="title")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin,
                default=0)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax,
                default=10)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisLabelFontSizeRevLabels <- jmvcore::OptionBool$new(
                "xAxisLabelFontSizeRevLabels",
                xAxisLabelFontSizeRevLabels,
                default=FALSE)
            private$..legendTitle <- jmvcore::OptionString$new(
                "legendTitle",
                legendTitle,
                default="")
            private$..legendTitleFontSize <- jmvcore::OptionNumber$new(
                "legendTitleFontSize",
                legendTitleFontSize,
                default=16)
            private$..legendTitleFontFace <- jmvcore::OptionList$new(
                "legendTitleFontFace",
                legendTitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..legendLabelFontSize <- jmvcore::OptionNumber$new(
                "legendLabelFontSize",
                legendLabelFontSize,
                default=16)
            private$..legendLabelFontFace <- jmvcore::OptionList$new(
                "legendLabelFontFace",
                legendLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..legendKeyWidth <- jmvcore::OptionNumber$new(
                "legendKeyWidth",
                legendKeyWidth,
                default=0.6,
                min=0)
            private$..legendKeyHeight <- jmvcore::OptionNumber$new(
                "legendKeyHeight",
                legendKeyHeight,
                default=0.6,
                min=0)
            private$..legenPositionType <- jmvcore::OptionList$new(
                "legenPositionType",
                legenPositionType,
                options=list(
                    "outside",
                    "inside",
                    "hide"),
                default="outside")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "top",
                    "right",
                    "bottom",
                    "left"),
                default="right")
            private$..legendJustification <- jmvcore::OptionList$new(
                "legendJustification",
                legendJustification,
                options=list(
                    "center",
                    "top",
                    "right",
                    "bottom",
                    "left"),
                default="center")
            private$..legendPositionX <- jmvcore::OptionNumber$new(
                "legendPositionX",
                legendPositionX,
                default=0.8,
                min=0,
                max=1)
            private$..legendPositionY <- jmvcore::OptionNumber$new(
                "legendPositionY",
                legendPositionY,
                default=0.5,
                min=0,
                max=1)
            private$..legendDirection <- jmvcore::OptionList$new(
                "legendDirection",
                legendDirection,
                options=list(
                    "horizontal",
                    "vertical"),
                default="vertical")
            private$..groupBarType <- jmvcore::OptionList$new(
                "groupBarType",
                groupBarType,
                options=list(
                    "grouped",
                    "stacked"),
                default="grouped")

            self$.addOption(private$..mode)
            self$.addOption(private$..catvar)
            self$.addOption(private$..catgroup)
            self$.addOption(private$..convar)
            self$.addOption(private$..congroup1)
            self$.addOption(private$..congroup2)
            self$.addOption(private$..counts)
            self$.addOption(private$..countsLabels)
            self$.addOption(private$..countsgroup)
            self$.addOption(private$..flipAxes)
            self$.addOption(private$..barWidth)
            self$.addOption(private$..valueLabels)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..errorBars)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..errorBarWidth)
            self$.addOption(private$..errorBarSize)
            self$.addOption(private$..title)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..subtitle)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..caption)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..xLabel)
            self$.addOption(private$..xLabelAlign)
            self$.addOption(private$..xLabelFontSize)
            self$.addOption(private$..xLabelFontFace)
            self$.addOption(private$..yLabel)
            self$.addOption(private$..yLabelAlign)
            self$.addOption(private$..yLabelFontSize)
            self$.addOption(private$..yLabelFontFace)
            self$.addOption(private$..titleType)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..xAxisLabelFontSizeRevLabels)
            self$.addOption(private$..legendTitle)
            self$.addOption(private$..legendTitleFontSize)
            self$.addOption(private$..legendTitleFontFace)
            self$.addOption(private$..legendLabelFontSize)
            self$.addOption(private$..legendLabelFontFace)
            self$.addOption(private$..legendKeyWidth)
            self$.addOption(private$..legendKeyHeight)
            self$.addOption(private$..legenPositionType)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..legendJustification)
            self$.addOption(private$..legendPositionX)
            self$.addOption(private$..legendPositionY)
            self$.addOption(private$..legendDirection)
            self$.addOption(private$..groupBarType)
        }),
    active = list(
        mode = function() private$..mode$value,
        catvar = function() private$..catvar$value,
        catgroup = function() private$..catgroup$value,
        convar = function() private$..convar$value,
        congroup1 = function() private$..congroup1$value,
        congroup2 = function() private$..congroup2$value,
        counts = function() private$..counts$value,
        countsLabels = function() private$..countsLabels$value,
        countsgroup = function() private$..countsgroup$value,
        flipAxes = function() private$..flipAxes$value,
        barWidth = function() private$..barWidth$value,
        valueLabels = function() private$..valueLabels$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        errorBars = function() private$..errorBars$value,
        ciWidth = function() private$..ciWidth$value,
        errorBarWidth = function() private$..errorBarWidth$value,
        errorBarSize = function() private$..errorBarSize$value,
        title = function() private$..title$value,
        titleAlign = function() private$..titleAlign$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleFontFace = function() private$..titleFontFace$value,
        subtitle = function() private$..subtitle$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        caption = function() private$..caption$value,
        captionAlign = function() private$..captionAlign$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionFontFace = function() private$..captionFontFace$value,
        xLabel = function() private$..xLabel$value,
        xLabelAlign = function() private$..xLabelAlign$value,
        xLabelFontSize = function() private$..xLabelFontSize$value,
        xLabelFontFace = function() private$..xLabelFontFace$value,
        yLabel = function() private$..yLabel$value,
        yLabelAlign = function() private$..yLabelAlign$value,
        yLabelFontSize = function() private$..yLabelFontSize$value,
        yLabelFontFace = function() private$..yLabelFontFace$value,
        titleType = function() private$..titleType$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        xAxisLabelFontSizeRevLabels = function() private$..xAxisLabelFontSizeRevLabels$value,
        legendTitle = function() private$..legendTitle$value,
        legendTitleFontSize = function() private$..legendTitleFontSize$value,
        legendTitleFontFace = function() private$..legendTitleFontFace$value,
        legendLabelFontSize = function() private$..legendLabelFontSize$value,
        legendLabelFontFace = function() private$..legendLabelFontFace$value,
        legendKeyWidth = function() private$..legendKeyWidth$value,
        legendKeyHeight = function() private$..legendKeyHeight$value,
        legenPositionType = function() private$..legenPositionType$value,
        legendPosition = function() private$..legendPosition$value,
        legendJustification = function() private$..legendJustification$value,
        legendPositionX = function() private$..legendPositionX$value,
        legendPositionY = function() private$..legendPositionY$value,
        legendDirection = function() private$..legendDirection$value,
        groupBarType = function() private$..groupBarType$value),
    private = list(
        ..mode = NA,
        ..catvar = NA,
        ..catgroup = NA,
        ..convar = NA,
        ..congroup1 = NA,
        ..congroup2 = NA,
        ..counts = NA,
        ..countsLabels = NA,
        ..countsgroup = NA,
        ..flipAxes = NA,
        ..barWidth = NA,
        ..valueLabels = NA,
        ..width = NA,
        ..height = NA,
        ..errorBars = NA,
        ..ciWidth = NA,
        ..errorBarWidth = NA,
        ..errorBarSize = NA,
        ..title = NA,
        ..titleAlign = NA,
        ..titleFontSize = NA,
        ..titleFontFace = NA,
        ..subtitle = NA,
        ..subtitleAlign = NA,
        ..subtitleFontSize = NA,
        ..subtitleFontFace = NA,
        ..caption = NA,
        ..captionAlign = NA,
        ..captionFontSize = NA,
        ..captionFontFace = NA,
        ..xLabel = NA,
        ..xLabelAlign = NA,
        ..xLabelFontSize = NA,
        ..xLabelFontFace = NA,
        ..yLabel = NA,
        ..yLabelAlign = NA,
        ..yLabelFontSize = NA,
        ..yLabelFontFace = NA,
        ..titleType = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA,
        ..xAxisLabelFontSizeRevLabels = NA,
        ..legendTitle = NA,
        ..legendTitleFontSize = NA,
        ..legendTitleFontFace = NA,
        ..legendLabelFontSize = NA,
        ..legendLabelFontFace = NA,
        ..legendKeyWidth = NA,
        ..legendKeyHeight = NA,
        ..legenPositionType = NA,
        ..legendPosition = NA,
        ..legendJustification = NA,
        ..legendPositionX = NA,
        ..legendPositionY = NA,
        ..legendDirection = NA,
        ..groupBarType = NA)
)

jmvbarResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvbarResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bar Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=500,
                height=500,
                renderFun=".barPlot"))}))

jmvbarBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvbarBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "scatr",
                name = "jmvbar",
                version = c(1,0,0),
                options = options,
                results = jmvbarResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bar Plot
#'
#' 
#' @param mode .
#' @param data .
#' @param catvar .
#' @param catgroup .
#' @param convar .
#' @param congroup1 .
#' @param congroup2 .
#' @param counts .
#' @param countsLabels .
#' @param countsgroup .
#' @param flipAxes .
#' @param barWidth .
#' @param valueLabels .
#' @param width .
#' @param height .
#' @param errorBars .
#' @param ciWidth .
#' @param errorBarWidth .
#' @param errorBarSize .
#' @param title .
#' @param titleAlign .
#' @param titleFontSize .
#' @param titleFontFace .
#' @param subtitle .
#' @param subtitleAlign .
#' @param subtitleFontSize .
#' @param subtitleFontFace .
#' @param caption .
#' @param captionAlign .
#' @param captionFontSize .
#' @param captionFontFace .
#' @param xLabel .
#' @param xLabelAlign .
#' @param xLabelFontSize .
#' @param xLabelFontFace .
#' @param yLabel .
#' @param yLabelAlign .
#' @param yLabelFontSize .
#' @param yLabelFontFace .
#' @param titleType .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @param xAxisLabelFontSizeRevLabels .
#' @param legendTitle .
#' @param legendTitleFontSize .
#' @param legendTitleFontFace .
#' @param legendLabelFontSize .
#' @param legendLabelFontFace .
#' @param legendKeyWidth .
#' @param legendKeyHeight .
#' @param legenPositionType .
#' @param legendPosition .
#' @param legendJustification .
#' @param legendPositionX .
#' @param legendPositionY .
#' @param legendDirection .
#' @param groupBarType .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image containing the bar plot \cr
#' }
#'
#' @export
jmvbar <- function(
    mode = "categorical",
    data,
    catvar = NULL,
    catgroup = NULL,
    convar = NULL,
    congroup1 = NULL,
    congroup2 = NULL,
    counts = NULL,
    countsLabels = NULL,
    countsgroup = NULL,
    flipAxes = FALSE,
    barWidth = 0.9,
    valueLabels = FALSE,
    width = 500,
    height = 500,
    errorBars = "none",
    ciWidth = 95,
    errorBarWidth = 0.1,
    errorBarSize = 0.5,
    title = "",
    titleAlign = "center",
    titleFontSize = 16,
    titleFontFace = "plain",
    subtitle = "",
    subtitleAlign = "left",
    subtitleFontSize = 16,
    subtitleFontFace = "plain",
    caption = "",
    captionAlign = "right",
    captionFontSize = 12,
    captionFontFace = "plain",
    xLabel = "",
    xLabelAlign = "center",
    xLabelFontSize = 16,
    xLabelFontFace = "plain",
    yLabel = "",
    yLabelAlign = "center",
    yLabelFontSize = 16,
    yLabelFontFace = "plain",
    titleType = "title",
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    yAxisRangeType = "auto",
    yAxisRangeMin = 0,
    yAxisRangeMax = 10,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0,
    xAxisLabelFontSizeRevLabels = FALSE,
    legendTitle = "",
    legendTitleFontSize = 16,
    legendTitleFontFace = "plain",
    legendLabelFontSize = 16,
    legendLabelFontFace = "plain",
    legendKeyWidth = 0.6,
    legendKeyHeight = 0.6,
    legenPositionType = "outside",
    legendPosition = "right",
    legendJustification = "center",
    legendPositionX = 0.8,
    legendPositionY = 0.5,
    legendDirection = "vertical",
    groupBarType = "grouped") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvbar requires jmvcore to be installed (restart may be required)")

    if ( ! missing(catvar)) catvar <- jmvcore::resolveQuo(jmvcore::enquo(catvar))
    if ( ! missing(catgroup)) catgroup <- jmvcore::resolveQuo(jmvcore::enquo(catgroup))
    if ( ! missing(convar)) convar <- jmvcore::resolveQuo(jmvcore::enquo(convar))
    if ( ! missing(congroup1)) congroup1 <- jmvcore::resolveQuo(jmvcore::enquo(congroup1))
    if ( ! missing(congroup2)) congroup2 <- jmvcore::resolveQuo(jmvcore::enquo(congroup2))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if ( ! missing(countsLabels)) countsLabels <- jmvcore::resolveQuo(jmvcore::enquo(countsLabels))
    if ( ! missing(countsgroup)) countsgroup <- jmvcore::resolveQuo(jmvcore::enquo(countsgroup))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(catvar), catvar, NULL),
            `if`( ! missing(catgroup), catgroup, NULL),
            `if`( ! missing(convar), convar, NULL),
            `if`( ! missing(congroup1), congroup1, NULL),
            `if`( ! missing(congroup2), congroup2, NULL),
            `if`( ! missing(counts), counts, NULL),
            `if`( ! missing(countsLabels), countsLabels, NULL),
            `if`( ! missing(countsgroup), countsgroup, NULL))

    for (v in catvar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in catgroup) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in congroup1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in congroup2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in countsLabels) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in countsgroup) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jmvbarOptions$new(
        mode = mode,
        catvar = catvar,
        catgroup = catgroup,
        convar = convar,
        congroup1 = congroup1,
        congroup2 = congroup2,
        counts = counts,
        countsLabels = countsLabels,
        countsgroup = countsgroup,
        flipAxes = flipAxes,
        barWidth = barWidth,
        valueLabels = valueLabels,
        width = width,
        height = height,
        errorBars = errorBars,
        ciWidth = ciWidth,
        errorBarWidth = errorBarWidth,
        errorBarSize = errorBarSize,
        title = title,
        titleAlign = titleAlign,
        titleFontSize = titleFontSize,
        titleFontFace = titleFontFace,
        subtitle = subtitle,
        subtitleAlign = subtitleAlign,
        subtitleFontSize = subtitleFontSize,
        subtitleFontFace = subtitleFontFace,
        caption = caption,
        captionAlign = captionAlign,
        captionFontSize = captionFontSize,
        captionFontFace = captionFontFace,
        xLabel = xLabel,
        xLabelAlign = xLabelAlign,
        xLabelFontSize = xLabelFontSize,
        xLabelFontFace = xLabelFontFace,
        yLabel = yLabel,
        yLabelAlign = yLabelAlign,
        yLabelFontSize = yLabelFontSize,
        yLabelFontFace = yLabelFontFace,
        titleType = titleType,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation,
        xAxisLabelFontSizeRevLabels = xAxisLabelFontSizeRevLabels,
        legendTitle = legendTitle,
        legendTitleFontSize = legendTitleFontSize,
        legendTitleFontFace = legendTitleFontFace,
        legendLabelFontSize = legendLabelFontSize,
        legendLabelFontFace = legendLabelFontFace,
        legendKeyWidth = legendKeyWidth,
        legendKeyHeight = legendKeyHeight,
        legenPositionType = legenPositionType,
        legendPosition = legendPosition,
        legendJustification = legendJustification,
        legendPositionX = legendPositionX,
        legendPositionY = legendPositionY,
        legendDirection = legendDirection,
        groupBarType = groupBarType)

    analysis <- jmvbarClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

