
# This file is automatically generated, you probably don't want to edit this

jmvboxOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvboxOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            group1 = NULL,
            group2 = NULL,
            flipAxes = FALSE,
            notch = FALSE,
            boxWidth = 0.5,
            outliers = TRUE,
            width = 500,
            height = 500,
            title = "",
            titleAlign = "center",
            titleFontSize = 16,
            titleFontFace = "plain",
            subtitle = "",
            subtitleAlign = "left",
            subtitleFontSize = 16,
            subtitleFontFace = "plain",
            caption = "",
            captionAlign = "right",
            captionFontSize = 12,
            captionFontFace = "plain",
            xLabel = "",
            xLabelAlign = "center",
            xLabelFontSize = 16,
            xLabelFontFace = "plain",
            yLabel = "",
            yLabelAlign = "center",
            yLabelFontSize = 16,
            yLabelFontFace = "plain",
            titleType = "title",
            yAxisLabelFontSize = 12,
            yAxisRangeType = "auto",
            yAxisRangeMin = 0,
            yAxisRangeMax = 10,
            yAxisLabelRotation = 0,
            xAxisLabelFontSize = 12,
            xAxisLabelFontSizeRevLabels = FALSE,
            xAxisLabelRotation = 0,
            legendTitle = "",
            legendTitleFontSize = 16,
            legendTitleFontFace = "plain",
            legendLabelFontSize = 16,
            legendLabelFontFace = "plain",
            legendKeyWidth = 0.6,
            legendKeyHeight = 0.6,
            legenPositionType = "outside",
            legendPosition = "right",
            legendJustification = "center",
            legendPositionX = 0.8,
            legendPositionY = 0.5,
            legendDirection = "vertical", ...) {

            super$initialize(
                package="scatr",
                name="jmvbox",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group1 <- jmvcore::OptionVariable$new(
                "group1",
                group1,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..group2 <- jmvcore::OptionVariable$new(
                "group2",
                group2,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..flipAxes <- jmvcore::OptionBool$new(
                "flipAxes",
                flipAxes,
                default=FALSE)
            private$..notch <- jmvcore::OptionBool$new(
                "notch",
                notch,
                default=FALSE)
            private$..boxWidth <- jmvcore::OptionNumber$new(
                "boxWidth",
                boxWidth,
                default=0.5,
                min=0,
                max=1)
            private$..outliers <- jmvcore::OptionBool$new(
                "outliers",
                outliers,
                default=TRUE)
            private$..width <- jmvcore::OptionNumber$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionNumber$new(
                "height",
                height,
                default=500)
            private$..title <- jmvcore::OptionString$new(
                "title",
                title,
                default="")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..titleFontSize <- jmvcore::OptionNumber$new(
                "titleFontSize",
                titleFontSize,
                default=16)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..subtitle <- jmvcore::OptionString$new(
                "subtitle",
                subtitle,
                default="")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="left")
            private$..subtitleFontSize <- jmvcore::OptionNumber$new(
                "subtitleFontSize",
                subtitleFontSize,
                default=16)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..caption <- jmvcore::OptionString$new(
                "caption",
                caption,
                default="")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="right")
            private$..captionFontSize <- jmvcore::OptionNumber$new(
                "captionFontSize",
                captionFontSize,
                default=12)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..xLabel <- jmvcore::OptionString$new(
                "xLabel",
                xLabel,
                default="")
            private$..xLabelAlign <- jmvcore::OptionList$new(
                "xLabelAlign",
                xLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..xLabelFontSize <- jmvcore::OptionNumber$new(
                "xLabelFontSize",
                xLabelFontSize,
                default=16)
            private$..xLabelFontFace <- jmvcore::OptionList$new(
                "xLabelFontFace",
                xLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..yLabel <- jmvcore::OptionString$new(
                "yLabel",
                yLabel,
                default="")
            private$..yLabelAlign <- jmvcore::OptionList$new(
                "yLabelAlign",
                yLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..yLabelFontSize <- jmvcore::OptionNumber$new(
                "yLabelFontSize",
                yLabelFontSize,
                default=16)
            private$..yLabelFontFace <- jmvcore::OptionList$new(
                "yLabelFontFace",
                yLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..titleType <- jmvcore::OptionList$new(
                "titleType",
                titleType,
                options=list(
                    "title",
                    "subtitle",
                    "caption",
                    "xTitle",
                    "yTitle"),
                default="title")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin,
                default=0)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax,
                default=10)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelFontSizeRevLabels <- jmvcore::OptionBool$new(
                "xAxisLabelFontSizeRevLabels",
                xAxisLabelFontSizeRevLabels,
                default=FALSE)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..legendTitle <- jmvcore::OptionString$new(
                "legendTitle",
                legendTitle,
                default="")
            private$..legendTitleFontSize <- jmvcore::OptionNumber$new(
                "legendTitleFontSize",
                legendTitleFontSize,
                default=16)
            private$..legendTitleFontFace <- jmvcore::OptionList$new(
                "legendTitleFontFace",
                legendTitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..legendLabelFontSize <- jmvcore::OptionNumber$new(
                "legendLabelFontSize",
                legendLabelFontSize,
                default=16)
            private$..legendLabelFontFace <- jmvcore::OptionList$new(
                "legendLabelFontFace",
                legendLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..legendKeyWidth <- jmvcore::OptionNumber$new(
                "legendKeyWidth",
                legendKeyWidth,
                default=0.6,
                min=0)
            private$..legendKeyHeight <- jmvcore::OptionNumber$new(
                "legendKeyHeight",
                legendKeyHeight,
                default=0.6,
                min=0)
            private$..legenPositionType <- jmvcore::OptionList$new(
                "legenPositionType",
                legenPositionType,
                options=list(
                    "outside",
                    "inside",
                    "hide"),
                default="outside")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "top",
                    "right",
                    "bottom",
                    "left"),
                default="right")
            private$..legendJustification <- jmvcore::OptionList$new(
                "legendJustification",
                legendJustification,
                options=list(
                    "center",
                    "top",
                    "right",
                    "bottom",
                    "left"),
                default="center")
            private$..legendPositionX <- jmvcore::OptionNumber$new(
                "legendPositionX",
                legendPositionX,
                default=0.8,
                min=0,
                max=1)
            private$..legendPositionY <- jmvcore::OptionNumber$new(
                "legendPositionY",
                legendPositionY,
                default=0.5,
                min=0,
                max=1)
            private$..legendDirection <- jmvcore::OptionList$new(
                "legendDirection",
                legendDirection,
                options=list(
                    "horizontal",
                    "vertical"),
                default="vertical")

            self$.addOption(private$..var)
            self$.addOption(private$..group1)
            self$.addOption(private$..group2)
            self$.addOption(private$..flipAxes)
            self$.addOption(private$..notch)
            self$.addOption(private$..boxWidth)
            self$.addOption(private$..outliers)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..title)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..subtitle)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..caption)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..xLabel)
            self$.addOption(private$..xLabelAlign)
            self$.addOption(private$..xLabelFontSize)
            self$.addOption(private$..xLabelFontFace)
            self$.addOption(private$..yLabel)
            self$.addOption(private$..yLabelAlign)
            self$.addOption(private$..yLabelFontSize)
            self$.addOption(private$..yLabelFontFace)
            self$.addOption(private$..titleType)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelFontSizeRevLabels)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..legendTitle)
            self$.addOption(private$..legendTitleFontSize)
            self$.addOption(private$..legendTitleFontFace)
            self$.addOption(private$..legendLabelFontSize)
            self$.addOption(private$..legendLabelFontFace)
            self$.addOption(private$..legendKeyWidth)
            self$.addOption(private$..legendKeyHeight)
            self$.addOption(private$..legenPositionType)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..legendJustification)
            self$.addOption(private$..legendPositionX)
            self$.addOption(private$..legendPositionY)
            self$.addOption(private$..legendDirection)
        }),
    active = list(
        var = function() private$..var$value,
        group1 = function() private$..group1$value,
        group2 = function() private$..group2$value,
        flipAxes = function() private$..flipAxes$value,
        notch = function() private$..notch$value,
        boxWidth = function() private$..boxWidth$value,
        outliers = function() private$..outliers$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        title = function() private$..title$value,
        titleAlign = function() private$..titleAlign$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleFontFace = function() private$..titleFontFace$value,
        subtitle = function() private$..subtitle$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        caption = function() private$..caption$value,
        captionAlign = function() private$..captionAlign$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionFontFace = function() private$..captionFontFace$value,
        xLabel = function() private$..xLabel$value,
        xLabelAlign = function() private$..xLabelAlign$value,
        xLabelFontSize = function() private$..xLabelFontSize$value,
        xLabelFontFace = function() private$..xLabelFontFace$value,
        yLabel = function() private$..yLabel$value,
        yLabelAlign = function() private$..yLabelAlign$value,
        yLabelFontSize = function() private$..yLabelFontSize$value,
        yLabelFontFace = function() private$..yLabelFontFace$value,
        titleType = function() private$..titleType$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelFontSizeRevLabels = function() private$..xAxisLabelFontSizeRevLabels$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        legendTitle = function() private$..legendTitle$value,
        legendTitleFontSize = function() private$..legendTitleFontSize$value,
        legendTitleFontFace = function() private$..legendTitleFontFace$value,
        legendLabelFontSize = function() private$..legendLabelFontSize$value,
        legendLabelFontFace = function() private$..legendLabelFontFace$value,
        legendKeyWidth = function() private$..legendKeyWidth$value,
        legendKeyHeight = function() private$..legendKeyHeight$value,
        legenPositionType = function() private$..legenPositionType$value,
        legendPosition = function() private$..legendPosition$value,
        legendJustification = function() private$..legendJustification$value,
        legendPositionX = function() private$..legendPositionX$value,
        legendPositionY = function() private$..legendPositionY$value,
        legendDirection = function() private$..legendDirection$value),
    private = list(
        ..var = NA,
        ..group1 = NA,
        ..group2 = NA,
        ..flipAxes = NA,
        ..notch = NA,
        ..boxWidth = NA,
        ..outliers = NA,
        ..width = NA,
        ..height = NA,
        ..title = NA,
        ..titleAlign = NA,
        ..titleFontSize = NA,
        ..titleFontFace = NA,
        ..subtitle = NA,
        ..subtitleAlign = NA,
        ..subtitleFontSize = NA,
        ..subtitleFontFace = NA,
        ..caption = NA,
        ..captionAlign = NA,
        ..captionFontSize = NA,
        ..captionFontFace = NA,
        ..xLabel = NA,
        ..xLabelAlign = NA,
        ..xLabelFontSize = NA,
        ..xLabelFontFace = NA,
        ..yLabel = NA,
        ..yLabelAlign = NA,
        ..yLabelFontSize = NA,
        ..yLabelFontFace = NA,
        ..titleType = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..yAxisLabelRotation = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelFontSizeRevLabels = NA,
        ..xAxisLabelRotation = NA,
        ..legendTitle = NA,
        ..legendTitleFontSize = NA,
        ..legendTitleFontFace = NA,
        ..legendLabelFontSize = NA,
        ..legendLabelFontFace = NA,
        ..legendKeyWidth = NA,
        ..legendKeyHeight = NA,
        ..legenPositionType = NA,
        ..legendPosition = NA,
        ..legendJustification = NA,
        ..legendPositionX = NA,
        ..legendPositionY = NA,
        ..legendDirection = NA)
)

jmvboxResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvboxResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Box Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=500,
                height=500,
                renderFun=".boxPlot"))}))

jmvboxBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvboxBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "scatr",
                name = "jmvbox",
                version = c(1,0,0),
                options = options,
                results = jmvboxResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Box Plot
#'
#' 
#' @param data .
#' @param var .
#' @param group1 .
#' @param group2 .
#' @param flipAxes .
#' @param notch .
#' @param boxWidth .
#' @param outliers .
#' @param width .
#' @param height .
#' @param title .
#' @param titleAlign .
#' @param titleFontSize .
#' @param titleFontFace .
#' @param subtitle .
#' @param subtitleAlign .
#' @param subtitleFontSize .
#' @param subtitleFontFace .
#' @param caption .
#' @param captionAlign .
#' @param captionFontSize .
#' @param captionFontFace .
#' @param xLabel .
#' @param xLabelAlign .
#' @param xLabelFontSize .
#' @param xLabelFontFace .
#' @param yLabel .
#' @param yLabelAlign .
#' @param yLabelFontSize .
#' @param yLabelFontFace .
#' @param titleType .
#' @param yAxisLabelFontSize .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param yAxisLabelRotation .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelFontSizeRevLabels .
#' @param xAxisLabelRotation .
#' @param legendTitle .
#' @param legendTitleFontSize .
#' @param legendTitleFontFace .
#' @param legendLabelFontSize .
#' @param legendLabelFontFace .
#' @param legendKeyWidth .
#' @param legendKeyHeight .
#' @param legenPositionType .
#' @param legendPosition .
#' @param legendJustification .
#' @param legendPositionX .
#' @param legendPositionY .
#' @param legendDirection .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image containing the box plot \cr
#' }
#'
#' @export
jmvbox <- function(
    data,
    var,
    group1 = NULL,
    group2 = NULL,
    flipAxes = FALSE,
    notch = FALSE,
    boxWidth = 0.5,
    outliers = TRUE,
    width = 500,
    height = 500,
    title = "",
    titleAlign = "center",
    titleFontSize = 16,
    titleFontFace = "plain",
    subtitle = "",
    subtitleAlign = "left",
    subtitleFontSize = 16,
    subtitleFontFace = "plain",
    caption = "",
    captionAlign = "right",
    captionFontSize = 12,
    captionFontFace = "plain",
    xLabel = "",
    xLabelAlign = "center",
    xLabelFontSize = 16,
    xLabelFontFace = "plain",
    yLabel = "",
    yLabelAlign = "center",
    yLabelFontSize = 16,
    yLabelFontFace = "plain",
    titleType = "title",
    yAxisLabelFontSize = 12,
    yAxisRangeType = "auto",
    yAxisRangeMin = 0,
    yAxisRangeMax = 10,
    yAxisLabelRotation = 0,
    xAxisLabelFontSize = 12,
    xAxisLabelFontSizeRevLabels = FALSE,
    xAxisLabelRotation = 0,
    legendTitle = "",
    legendTitleFontSize = 16,
    legendTitleFontFace = "plain",
    legendLabelFontSize = 16,
    legendLabelFontFace = "plain",
    legendKeyWidth = 0.6,
    legendKeyHeight = 0.6,
    legenPositionType = "outside",
    legendPosition = "right",
    legendJustification = "center",
    legendPositionX = 0.8,
    legendPositionY = 0.5,
    legendDirection = "vertical") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvbox requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if ( ! missing(group1)) group1 <- jmvcore::resolveQuo(jmvcore::enquo(group1))
    if ( ! missing(group2)) group2 <- jmvcore::resolveQuo(jmvcore::enquo(group2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL),
            `if`( ! missing(group1), group1, NULL),
            `if`( ! missing(group2), group2, NULL))

    for (v in group1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jmvboxOptions$new(
        var = var,
        group1 = group1,
        group2 = group2,
        flipAxes = flipAxes,
        notch = notch,
        boxWidth = boxWidth,
        outliers = outliers,
        width = width,
        height = height,
        title = title,
        titleAlign = titleAlign,
        titleFontSize = titleFontSize,
        titleFontFace = titleFontFace,
        subtitle = subtitle,
        subtitleAlign = subtitleAlign,
        subtitleFontSize = subtitleFontSize,
        subtitleFontFace = subtitleFontFace,
        caption = caption,
        captionAlign = captionAlign,
        captionFontSize = captionFontSize,
        captionFontFace = captionFontFace,
        xLabel = xLabel,
        xLabelAlign = xLabelAlign,
        xLabelFontSize = xLabelFontSize,
        xLabelFontFace = xLabelFontFace,
        yLabel = yLabel,
        yLabelAlign = yLabelAlign,
        yLabelFontSize = yLabelFontSize,
        yLabelFontFace = yLabelFontFace,
        titleType = titleType,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        yAxisLabelRotation = yAxisLabelRotation,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelFontSizeRevLabels = xAxisLabelFontSizeRevLabels,
        xAxisLabelRotation = xAxisLabelRotation,
        legendTitle = legendTitle,
        legendTitleFontSize = legendTitleFontSize,
        legendTitleFontFace = legendTitleFontFace,
        legendLabelFontSize = legendLabelFontSize,
        legendLabelFontFace = legendLabelFontFace,
        legendKeyWidth = legendKeyWidth,
        legendKeyHeight = legendKeyHeight,
        legenPositionType = legenPositionType,
        legendPosition = legendPosition,
        legendJustification = legendJustification,
        legendPositionX = legendPositionX,
        legendPositionY = legendPositionY,
        legendDirection = legendDirection)

    analysis <- jmvboxClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

