
# This file is automatically generated, you probably don't want to edit this

jmvlineOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvlineOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "individual",
            x = NULL,
            y = NULL,
            group = NULL,
            flipAxes = FALSE,
            line = TRUE,
            lineSize = 0.5,
            point = TRUE,
            pointSize = 2,
            aggregateType = "mean",
            errorBars = "none",
            ciWidth = 95,
            errorBarWidth = 0.1,
            errorBarSize = 0.5,
            title = "",
            titleAlign = "center",
            titleFontSize = 16,
            titleFontFace = "plain",
            subtitle = "",
            subtitleAlign = "left",
            subtitleFontSize = 16,
            subtitleFontFace = "plain",
            caption = "",
            captionAlign = "right",
            captionFontSize = 12,
            captionFontFace = "plain",
            xLabel = "",
            xLabelAlign = "center",
            xLabelFontSize = 16,
            xLabelFontFace = "plain",
            yLabel = "",
            yLabelAlign = "center",
            yLabelFontSize = 16,
            yLabelFontFace = "plain",
            titleType = "title",
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            yAxisRangeType = "auto",
            yAxisRangeMin = 0,
            yAxisRangeMax = 10,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0,
            legendTitle = "",
            legendTitleFontSize = 16,
            legendTitleFontFace = "plain",
            legendLabelFontSize = 16,
            legendLabelFontFace = "plain",
            legendKeyWidth = 1,
            legendKeyHeight = 0.6,
            legenPositionType = "outside",
            legendPosition = "right",
            legendJustification = "center",
            legendPositionX = 0.8,
            legendPositionY = 0.5,
            legendDirection = "vertical",
            groupPositionDodge = 0.5,
            groupColor = TRUE,
            groupLineType = FALSE,
            groupPointType = FALSE, ...) {

            super$initialize(
                package="scatr",
                name="jmvline",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "individual",
                    "aggregate"),
                default="individual")
            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..flipAxes <- jmvcore::OptionBool$new(
                "flipAxes",
                flipAxes,
                default=FALSE)
            private$..line <- jmvcore::OptionBool$new(
                "line",
                line,
                default=TRUE)
            private$..lineSize <- jmvcore::OptionNumber$new(
                "lineSize",
                lineSize,
                default=0.5)
            private$..point <- jmvcore::OptionBool$new(
                "point",
                point,
                default=TRUE)
            private$..pointSize <- jmvcore::OptionNumber$new(
                "pointSize",
                pointSize,
                default=2)
            private$..aggregateType <- jmvcore::OptionList$new(
                "aggregateType",
                aggregateType,
                options=list(
                    "mean",
                    "median"),
                default="mean")
            private$..errorBars <- jmvcore::OptionList$new(
                "errorBars",
                errorBars,
                options=list(
                    "none",
                    "sd",
                    "se",
                    "ci"),
                default="none")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=0,
                max=100)
            private$..errorBarWidth <- jmvcore::OptionNumber$new(
                "errorBarWidth",
                errorBarWidth,
                default=0.1,
                min=0)
            private$..errorBarSize <- jmvcore::OptionNumber$new(
                "errorBarSize",
                errorBarSize,
                default=0.5,
                min=0)
            private$..title <- jmvcore::OptionString$new(
                "title",
                title,
                default="")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..titleFontSize <- jmvcore::OptionNumber$new(
                "titleFontSize",
                titleFontSize,
                default=16)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..subtitle <- jmvcore::OptionString$new(
                "subtitle",
                subtitle,
                default="")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="left")
            private$..subtitleFontSize <- jmvcore::OptionNumber$new(
                "subtitleFontSize",
                subtitleFontSize,
                default=16)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..caption <- jmvcore::OptionString$new(
                "caption",
                caption,
                default="")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="right")
            private$..captionFontSize <- jmvcore::OptionNumber$new(
                "captionFontSize",
                captionFontSize,
                default=12)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..xLabel <- jmvcore::OptionString$new(
                "xLabel",
                xLabel,
                default="")
            private$..xLabelAlign <- jmvcore::OptionList$new(
                "xLabelAlign",
                xLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..xLabelFontSize <- jmvcore::OptionNumber$new(
                "xLabelFontSize",
                xLabelFontSize,
                default=16)
            private$..xLabelFontFace <- jmvcore::OptionList$new(
                "xLabelFontFace",
                xLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..yLabel <- jmvcore::OptionString$new(
                "yLabel",
                yLabel,
                default="")
            private$..yLabelAlign <- jmvcore::OptionList$new(
                "yLabelAlign",
                yLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..yLabelFontSize <- jmvcore::OptionNumber$new(
                "yLabelFontSize",
                yLabelFontSize,
                default=16)
            private$..yLabelFontFace <- jmvcore::OptionList$new(
                "yLabelFontFace",
                yLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..titleType <- jmvcore::OptionList$new(
                "titleType",
                titleType,
                options=list(
                    "title",
                    "subtitle",
                    "caption",
                    "xTitle",
                    "yTitle"),
                default="title")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin,
                default=0)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax,
                default=10)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..legendTitle <- jmvcore::OptionString$new(
                "legendTitle",
                legendTitle,
                default="")
            private$..legendTitleFontSize <- jmvcore::OptionNumber$new(
                "legendTitleFontSize",
                legendTitleFontSize,
                default=16)
            private$..legendTitleFontFace <- jmvcore::OptionList$new(
                "legendTitleFontFace",
                legendTitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..legendLabelFontSize <- jmvcore::OptionNumber$new(
                "legendLabelFontSize",
                legendLabelFontSize,
                default=16)
            private$..legendLabelFontFace <- jmvcore::OptionList$new(
                "legendLabelFontFace",
                legendLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..legendKeyWidth <- jmvcore::OptionNumber$new(
                "legendKeyWidth",
                legendKeyWidth,
                default=1,
                min=0)
            private$..legendKeyHeight <- jmvcore::OptionNumber$new(
                "legendKeyHeight",
                legendKeyHeight,
                default=0.6,
                min=0)
            private$..legenPositionType <- jmvcore::OptionList$new(
                "legenPositionType",
                legenPositionType,
                options=list(
                    "outside",
                    "inside",
                    "hide"),
                default="outside")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "top",
                    "right",
                    "bottom",
                    "left"),
                default="right")
            private$..legendJustification <- jmvcore::OptionList$new(
                "legendJustification",
                legendJustification,
                options=list(
                    "center",
                    "top",
                    "right",
                    "bottom",
                    "left"),
                default="center")
            private$..legendPositionX <- jmvcore::OptionNumber$new(
                "legendPositionX",
                legendPositionX,
                default=0.8,
                min=0,
                max=1)
            private$..legendPositionY <- jmvcore::OptionNumber$new(
                "legendPositionY",
                legendPositionY,
                default=0.5,
                min=0,
                max=1)
            private$..legendDirection <- jmvcore::OptionList$new(
                "legendDirection",
                legendDirection,
                options=list(
                    "horizontal",
                    "vertical"),
                default="vertical")
            private$..groupPositionDodge <- jmvcore::OptionNumber$new(
                "groupPositionDodge",
                groupPositionDodge,
                default=0.5)
            private$..groupColor <- jmvcore::OptionBool$new(
                "groupColor",
                groupColor,
                default=TRUE)
            private$..groupLineType <- jmvcore::OptionBool$new(
                "groupLineType",
                groupLineType,
                default=FALSE)
            private$..groupPointType <- jmvcore::OptionBool$new(
                "groupPointType",
                groupPointType,
                default=FALSE)

            self$.addOption(private$..mode)
            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..group)
            self$.addOption(private$..flipAxes)
            self$.addOption(private$..line)
            self$.addOption(private$..lineSize)
            self$.addOption(private$..point)
            self$.addOption(private$..pointSize)
            self$.addOption(private$..aggregateType)
            self$.addOption(private$..errorBars)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..errorBarWidth)
            self$.addOption(private$..errorBarSize)
            self$.addOption(private$..title)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..subtitle)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..caption)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..xLabel)
            self$.addOption(private$..xLabelAlign)
            self$.addOption(private$..xLabelFontSize)
            self$.addOption(private$..xLabelFontFace)
            self$.addOption(private$..yLabel)
            self$.addOption(private$..yLabelAlign)
            self$.addOption(private$..yLabelFontSize)
            self$.addOption(private$..yLabelFontFace)
            self$.addOption(private$..titleType)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..legendTitle)
            self$.addOption(private$..legendTitleFontSize)
            self$.addOption(private$..legendTitleFontFace)
            self$.addOption(private$..legendLabelFontSize)
            self$.addOption(private$..legendLabelFontFace)
            self$.addOption(private$..legendKeyWidth)
            self$.addOption(private$..legendKeyHeight)
            self$.addOption(private$..legenPositionType)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..legendJustification)
            self$.addOption(private$..legendPositionX)
            self$.addOption(private$..legendPositionY)
            self$.addOption(private$..legendDirection)
            self$.addOption(private$..groupPositionDodge)
            self$.addOption(private$..groupColor)
            self$.addOption(private$..groupLineType)
            self$.addOption(private$..groupPointType)
        }),
    active = list(
        mode = function() private$..mode$value,
        x = function() private$..x$value,
        y = function() private$..y$value,
        group = function() private$..group$value,
        flipAxes = function() private$..flipAxes$value,
        line = function() private$..line$value,
        lineSize = function() private$..lineSize$value,
        point = function() private$..point$value,
        pointSize = function() private$..pointSize$value,
        aggregateType = function() private$..aggregateType$value,
        errorBars = function() private$..errorBars$value,
        ciWidth = function() private$..ciWidth$value,
        errorBarWidth = function() private$..errorBarWidth$value,
        errorBarSize = function() private$..errorBarSize$value,
        title = function() private$..title$value,
        titleAlign = function() private$..titleAlign$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleFontFace = function() private$..titleFontFace$value,
        subtitle = function() private$..subtitle$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        caption = function() private$..caption$value,
        captionAlign = function() private$..captionAlign$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionFontFace = function() private$..captionFontFace$value,
        xLabel = function() private$..xLabel$value,
        xLabelAlign = function() private$..xLabelAlign$value,
        xLabelFontSize = function() private$..xLabelFontSize$value,
        xLabelFontFace = function() private$..xLabelFontFace$value,
        yLabel = function() private$..yLabel$value,
        yLabelAlign = function() private$..yLabelAlign$value,
        yLabelFontSize = function() private$..yLabelFontSize$value,
        yLabelFontFace = function() private$..yLabelFontFace$value,
        titleType = function() private$..titleType$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        legendTitle = function() private$..legendTitle$value,
        legendTitleFontSize = function() private$..legendTitleFontSize$value,
        legendTitleFontFace = function() private$..legendTitleFontFace$value,
        legendLabelFontSize = function() private$..legendLabelFontSize$value,
        legendLabelFontFace = function() private$..legendLabelFontFace$value,
        legendKeyWidth = function() private$..legendKeyWidth$value,
        legendKeyHeight = function() private$..legendKeyHeight$value,
        legenPositionType = function() private$..legenPositionType$value,
        legendPosition = function() private$..legendPosition$value,
        legendJustification = function() private$..legendJustification$value,
        legendPositionX = function() private$..legendPositionX$value,
        legendPositionY = function() private$..legendPositionY$value,
        legendDirection = function() private$..legendDirection$value,
        groupPositionDodge = function() private$..groupPositionDodge$value,
        groupColor = function() private$..groupColor$value,
        groupLineType = function() private$..groupLineType$value,
        groupPointType = function() private$..groupPointType$value),
    private = list(
        ..mode = NA,
        ..x = NA,
        ..y = NA,
        ..group = NA,
        ..flipAxes = NA,
        ..line = NA,
        ..lineSize = NA,
        ..point = NA,
        ..pointSize = NA,
        ..aggregateType = NA,
        ..errorBars = NA,
        ..ciWidth = NA,
        ..errorBarWidth = NA,
        ..errorBarSize = NA,
        ..title = NA,
        ..titleAlign = NA,
        ..titleFontSize = NA,
        ..titleFontFace = NA,
        ..subtitle = NA,
        ..subtitleAlign = NA,
        ..subtitleFontSize = NA,
        ..subtitleFontFace = NA,
        ..caption = NA,
        ..captionAlign = NA,
        ..captionFontSize = NA,
        ..captionFontFace = NA,
        ..xLabel = NA,
        ..xLabelAlign = NA,
        ..xLabelFontSize = NA,
        ..xLabelFontFace = NA,
        ..yLabel = NA,
        ..yLabelAlign = NA,
        ..yLabelFontSize = NA,
        ..yLabelFontFace = NA,
        ..titleType = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA,
        ..legendTitle = NA,
        ..legendTitleFontSize = NA,
        ..legendTitleFontFace = NA,
        ..legendLabelFontSize = NA,
        ..legendLabelFontFace = NA,
        ..legendKeyWidth = NA,
        ..legendKeyHeight = NA,
        ..legenPositionType = NA,
        ..legendPosition = NA,
        ..legendJustification = NA,
        ..legendPositionX = NA,
        ..legendPositionY = NA,
        ..legendDirection = NA,
        ..groupPositionDodge = NA,
        ..groupColor = NA,
        ..groupLineType = NA,
        ..groupPointType = NA)
)

jmvlineResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvlineResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Line Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=500,
                height=500,
                renderFun=".linePlot"))}))

jmvlineBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jmvlineBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "scatr",
                name = "jmvline",
                version = c(1,0,0),
                options = options,
                results = jmvlineResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Line Plot
#'
#' 
#' @param mode .
#' @param data .
#' @param x .
#' @param y .
#' @param group .
#' @param flipAxes .
#' @param line .
#' @param lineSize .
#' @param point .
#' @param pointSize .
#' @param aggregateType .
#' @param errorBars .
#' @param ciWidth .
#' @param errorBarWidth .
#' @param errorBarSize .
#' @param title .
#' @param titleAlign .
#' @param titleFontSize .
#' @param titleFontFace .
#' @param subtitle .
#' @param subtitleAlign .
#' @param subtitleFontSize .
#' @param subtitleFontFace .
#' @param caption .
#' @param captionAlign .
#' @param captionFontSize .
#' @param captionFontFace .
#' @param xLabel .
#' @param xLabelAlign .
#' @param xLabelFontSize .
#' @param xLabelFontFace .
#' @param yLabel .
#' @param yLabelAlign .
#' @param yLabelFontSize .
#' @param yLabelFontFace .
#' @param titleType .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @param legendTitle .
#' @param legendTitleFontSize .
#' @param legendTitleFontFace .
#' @param legendLabelFontSize .
#' @param legendLabelFontFace .
#' @param legendKeyWidth .
#' @param legendKeyHeight .
#' @param legenPositionType .
#' @param legendPosition .
#' @param legendJustification .
#' @param legendPositionX .
#' @param legendPositionY .
#' @param legendDirection .
#' @param groupPositionDodge .
#' @param groupColor .
#' @param groupLineType .
#' @param groupPointType .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image containing the line plot \cr
#' }
#'
#' @export
jmvline <- function(
    mode = "individual",
    data,
    x,
    y,
    group = NULL,
    flipAxes = FALSE,
    line = TRUE,
    lineSize = 0.5,
    point = TRUE,
    pointSize = 2,
    aggregateType = "mean",
    errorBars = "none",
    ciWidth = 95,
    errorBarWidth = 0.1,
    errorBarSize = 0.5,
    title = "",
    titleAlign = "center",
    titleFontSize = 16,
    titleFontFace = "plain",
    subtitle = "",
    subtitleAlign = "left",
    subtitleFontSize = 16,
    subtitleFontFace = "plain",
    caption = "",
    captionAlign = "right",
    captionFontSize = 12,
    captionFontFace = "plain",
    xLabel = "",
    xLabelAlign = "center",
    xLabelFontSize = 16,
    xLabelFontFace = "plain",
    yLabel = "",
    yLabelAlign = "center",
    yLabelFontSize = 16,
    yLabelFontFace = "plain",
    titleType = "title",
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    yAxisRangeType = "auto",
    yAxisRangeMin = 0,
    yAxisRangeMax = 10,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0,
    legendTitle = "",
    legendTitleFontSize = 16,
    legendTitleFontFace = "plain",
    legendLabelFontSize = 16,
    legendLabelFontFace = "plain",
    legendKeyWidth = 1,
    legendKeyHeight = 0.6,
    legenPositionType = "outside",
    legendPosition = "right",
    legendJustification = "center",
    legendPositionX = 0.8,
    legendPositionY = 0.5,
    legendDirection = "vertical",
    groupPositionDodge = 0.5,
    groupColor = TRUE,
    groupLineType = FALSE,
    groupPointType = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jmvline requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jmvlineOptions$new(
        mode = mode,
        x = x,
        y = y,
        group = group,
        flipAxes = flipAxes,
        line = line,
        lineSize = lineSize,
        point = point,
        pointSize = pointSize,
        aggregateType = aggregateType,
        errorBars = errorBars,
        ciWidth = ciWidth,
        errorBarWidth = errorBarWidth,
        errorBarSize = errorBarSize,
        title = title,
        titleAlign = titleAlign,
        titleFontSize = titleFontSize,
        titleFontFace = titleFontFace,
        subtitle = subtitle,
        subtitleAlign = subtitleAlign,
        subtitleFontSize = subtitleFontSize,
        subtitleFontFace = subtitleFontFace,
        caption = caption,
        captionAlign = captionAlign,
        captionFontSize = captionFontSize,
        captionFontFace = captionFontFace,
        xLabel = xLabel,
        xLabelAlign = xLabelAlign,
        xLabelFontSize = xLabelFontSize,
        xLabelFontFace = xLabelFontFace,
        yLabel = yLabel,
        yLabelAlign = yLabelAlign,
        yLabelFontSize = yLabelFontSize,
        yLabelFontFace = yLabelFontFace,
        titleType = titleType,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation,
        legendTitle = legendTitle,
        legendTitleFontSize = legendTitleFontSize,
        legendTitleFontFace = legendTitleFontFace,
        legendLabelFontSize = legendLabelFontSize,
        legendLabelFontFace = legendLabelFontFace,
        legendKeyWidth = legendKeyWidth,
        legendKeyHeight = legendKeyHeight,
        legenPositionType = legenPositionType,
        legendPosition = legendPosition,
        legendJustification = legendJustification,
        legendPositionX = legendPositionX,
        legendPositionY = legendPositionY,
        legendDirection = legendDirection,
        groupPositionDodge = groupPositionDodge,
        groupColor = groupColor,
        groupLineType = groupLineType,
        groupPointType = groupPointType)

    analysis <- jmvlineClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

