
# This file is automatically generated, you probably don't want to edit this

scatOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            group = NULL,
            flipAxes = FALSE,
            pointSize = 2,
            line = FALSE,
            lineMethod = "lm",
            lineSE = TRUE,
            width = 500,
            height = 500,
            title = "",
            titleAlign = "center",
            titleFontSize = 16,
            subtitle = "",
            subtitleAlign = "left",
            subtitleFontSize = 16,
            caption = "",
            captionAlign = "right",
            captionFontSize = 12,
            xLabel = "",
            xLabelAlign = "center",
            xLabelFontSize = 16,
            yLabel = "",
            yLabelAlign = "center",
            yLabelFontSize = 16,
            titleType = "title",
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            yAxisRangeType = "auto",
            yAxisRangeMin = NULL,
            yAxisRangeMax = NULL,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0,
            xAxisRangeType = "auto",
            xAxisRangeMin = NULL,
            xAxisRangeMax = NULL,
            legendTitle = "",
            legendTitleFontSize = 16,
            legendLabelFontSize = 16,
            legendKeyWidth = 0.6,
            legendKeyHeight = 0.6,
            legenPositionType = "outside",
            legendPosition = "right",
            legendJustification = "center",
            legendPositionX = 0.8,
            legendPositionY = 0.5,
            legendDirection = "vertical", ...) {

            super$initialize(
                package="scatr",
                name="scat",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..flipAxes <- jmvcore::OptionBool$new(
                "flipAxes",
                flipAxes,
                default=FALSE)
            private$..pointSize <- jmvcore::OptionNumber$new(
                "pointSize",
                pointSize,
                default=2)
            private$..line <- jmvcore::OptionBool$new(
                "line",
                line,
                default=FALSE)
            private$..lineMethod <- jmvcore::OptionList$new(
                "lineMethod",
                lineMethod,
                options=list(
                    "lm",
                    "loess"),
                default="lm")
            private$..lineSE <- jmvcore::OptionBool$new(
                "lineSE",
                lineSE,
                default=TRUE)
            private$..width <- jmvcore::OptionNumber$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionNumber$new(
                "height",
                height,
                default=500)
            private$..title <- jmvcore::OptionString$new(
                "title",
                title,
                default="")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..titleFontSize <- jmvcore::OptionNumber$new(
                "titleFontSize",
                titleFontSize,
                default=16)
            private$..subtitle <- jmvcore::OptionString$new(
                "subtitle",
                subtitle,
                default="")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="left")
            private$..subtitleFontSize <- jmvcore::OptionNumber$new(
                "subtitleFontSize",
                subtitleFontSize,
                default=16)
            private$..caption <- jmvcore::OptionString$new(
                "caption",
                caption,
                default="")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="right")
            private$..captionFontSize <- jmvcore::OptionNumber$new(
                "captionFontSize",
                captionFontSize,
                default=12)
            private$..xLabel <- jmvcore::OptionString$new(
                "xLabel",
                xLabel,
                default="")
            private$..xLabelAlign <- jmvcore::OptionList$new(
                "xLabelAlign",
                xLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..xLabelFontSize <- jmvcore::OptionNumber$new(
                "xLabelFontSize",
                xLabelFontSize,
                default=16)
            private$..yLabel <- jmvcore::OptionString$new(
                "yLabel",
                yLabel,
                default="")
            private$..yLabelAlign <- jmvcore::OptionList$new(
                "yLabelAlign",
                yLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..yLabelFontSize <- jmvcore::OptionNumber$new(
                "yLabelFontSize",
                yLabelFontSize,
                default=16)
            private$..titleType <- jmvcore::OptionList$new(
                "titleType",
                titleType,
                options=list(
                    "title",
                    "subtitle",
                    "caption",
                    "xTitle",
                    "yTitle"),
                default="title")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisRangeType <- jmvcore::OptionList$new(
                "xAxisRangeType",
                xAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..xAxisRangeMin <- jmvcore::OptionNumber$new(
                "xAxisRangeMin",
                xAxisRangeMin)
            private$..xAxisRangeMax <- jmvcore::OptionNumber$new(
                "xAxisRangeMax",
                xAxisRangeMax)
            private$..legendTitle <- jmvcore::OptionString$new(
                "legendTitle",
                legendTitle,
                default="")
            private$..legendTitleFontSize <- jmvcore::OptionNumber$new(
                "legendTitleFontSize",
                legendTitleFontSize,
                default=16)
            private$..legendLabelFontSize <- jmvcore::OptionNumber$new(
                "legendLabelFontSize",
                legendLabelFontSize,
                default=16)
            private$..legendKeyWidth <- jmvcore::OptionNumber$new(
                "legendKeyWidth",
                legendKeyWidth,
                default=0.6,
                min=0)
            private$..legendKeyHeight <- jmvcore::OptionNumber$new(
                "legendKeyHeight",
                legendKeyHeight,
                default=0.6,
                min=0)
            private$..legenPositionType <- jmvcore::OptionList$new(
                "legenPositionType",
                legenPositionType,
                options=list(
                    "outside",
                    "inside",
                    "hide"),
                default="outside")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "top",
                    "right",
                    "bottom",
                    "left"),
                default="right")
            private$..legendJustification <- jmvcore::OptionList$new(
                "legendJustification",
                legendJustification,
                options=list(
                    "center",
                    "top",
                    "right",
                    "bottom",
                    "left"),
                default="center")
            private$..legendPositionX <- jmvcore::OptionNumber$new(
                "legendPositionX",
                legendPositionX,
                default=0.8,
                min=0,
                max=1)
            private$..legendPositionY <- jmvcore::OptionNumber$new(
                "legendPositionY",
                legendPositionY,
                default=0.5,
                min=0,
                max=1)
            private$..legendDirection <- jmvcore::OptionList$new(
                "legendDirection",
                legendDirection,
                options=list(
                    "horizontal",
                    "vertical"),
                default="vertical")

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..group)
            self$.addOption(private$..flipAxes)
            self$.addOption(private$..pointSize)
            self$.addOption(private$..line)
            self$.addOption(private$..lineMethod)
            self$.addOption(private$..lineSE)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..title)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..subtitle)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..caption)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..xLabel)
            self$.addOption(private$..xLabelAlign)
            self$.addOption(private$..xLabelFontSize)
            self$.addOption(private$..yLabel)
            self$.addOption(private$..yLabelAlign)
            self$.addOption(private$..yLabelFontSize)
            self$.addOption(private$..titleType)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..xAxisRangeType)
            self$.addOption(private$..xAxisRangeMin)
            self$.addOption(private$..xAxisRangeMax)
            self$.addOption(private$..legendTitle)
            self$.addOption(private$..legendTitleFontSize)
            self$.addOption(private$..legendLabelFontSize)
            self$.addOption(private$..legendKeyWidth)
            self$.addOption(private$..legendKeyHeight)
            self$.addOption(private$..legenPositionType)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..legendJustification)
            self$.addOption(private$..legendPositionX)
            self$.addOption(private$..legendPositionY)
            self$.addOption(private$..legendDirection)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        group = function() private$..group$value,
        flipAxes = function() private$..flipAxes$value,
        pointSize = function() private$..pointSize$value,
        line = function() private$..line$value,
        lineMethod = function() private$..lineMethod$value,
        lineSE = function() private$..lineSE$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        title = function() private$..title$value,
        titleAlign = function() private$..titleAlign$value,
        titleFontSize = function() private$..titleFontSize$value,
        subtitle = function() private$..subtitle$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        caption = function() private$..caption$value,
        captionAlign = function() private$..captionAlign$value,
        captionFontSize = function() private$..captionFontSize$value,
        xLabel = function() private$..xLabel$value,
        xLabelAlign = function() private$..xLabelAlign$value,
        xLabelFontSize = function() private$..xLabelFontSize$value,
        yLabel = function() private$..yLabel$value,
        yLabelAlign = function() private$..yLabelAlign$value,
        yLabelFontSize = function() private$..yLabelFontSize$value,
        titleType = function() private$..titleType$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        xAxisRangeType = function() private$..xAxisRangeType$value,
        xAxisRangeMin = function() private$..xAxisRangeMin$value,
        xAxisRangeMax = function() private$..xAxisRangeMax$value,
        legendTitle = function() private$..legendTitle$value,
        legendTitleFontSize = function() private$..legendTitleFontSize$value,
        legendLabelFontSize = function() private$..legendLabelFontSize$value,
        legendKeyWidth = function() private$..legendKeyWidth$value,
        legendKeyHeight = function() private$..legendKeyHeight$value,
        legenPositionType = function() private$..legenPositionType$value,
        legendPosition = function() private$..legendPosition$value,
        legendJustification = function() private$..legendJustification$value,
        legendPositionX = function() private$..legendPositionX$value,
        legendPositionY = function() private$..legendPositionY$value,
        legendDirection = function() private$..legendDirection$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..group = NA,
        ..flipAxes = NA,
        ..pointSize = NA,
        ..line = NA,
        ..lineMethod = NA,
        ..lineSE = NA,
        ..width = NA,
        ..height = NA,
        ..title = NA,
        ..titleAlign = NA,
        ..titleFontSize = NA,
        ..subtitle = NA,
        ..subtitleAlign = NA,
        ..subtitleFontSize = NA,
        ..caption = NA,
        ..captionAlign = NA,
        ..captionFontSize = NA,
        ..xLabel = NA,
        ..xLabelAlign = NA,
        ..xLabelFontSize = NA,
        ..yLabel = NA,
        ..yLabelAlign = NA,
        ..yLabelFontSize = NA,
        ..titleType = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA,
        ..xAxisRangeType = NA,
        ..xAxisRangeMin = NA,
        ..xAxisRangeMax = NA,
        ..legendTitle = NA,
        ..legendTitleFontSize = NA,
        ..legendLabelFontSize = NA,
        ..legendKeyWidth = NA,
        ..legendKeyHeight = NA,
        ..legenPositionType = NA,
        ..legendPosition = NA,
        ..legendJustification = NA,
        ..legendPositionX = NA,
        ..legendPositionY = NA,
        ..legendDirection = NA)
)

scatResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scatterplot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=500,
                height=500,
                renderFun=".scatterPlot"))}))

scatBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "scatr",
                name = "scat",
                version = c(1,0,0),
                options = options,
                results = scatResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Scatterplot
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @param group .
#' @param flipAxes .
#' @param pointSize .
#' @param line .
#' @param lineMethod .
#' @param lineSE .
#' @param width .
#' @param height .
#' @param title .
#' @param titleAlign .
#' @param titleFontSize .
#' @param subtitle .
#' @param subtitleAlign .
#' @param subtitleFontSize .
#' @param caption .
#' @param captionAlign .
#' @param captionFontSize .
#' @param xLabel .
#' @param xLabelAlign .
#' @param xLabelFontSize .
#' @param yLabel .
#' @param yLabelAlign .
#' @param yLabelFontSize .
#' @param titleType .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @param xAxisRangeType .
#' @param xAxisRangeMin .
#' @param xAxisRangeMax .
#' @param legendTitle .
#' @param legendTitleFontSize .
#' @param legendLabelFontSize .
#' @param legendKeyWidth .
#' @param legendKeyHeight .
#' @param legenPositionType .
#' @param legendPosition .
#' @param legendJustification .
#' @param legendPositionX .
#' @param legendPositionY .
#' @param legendDirection .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image containing the scatter plot \cr
#' }
#'
#' @export
scat <- function(
    data,
    x,
    y,
    group,
    flipAxes = FALSE,
    pointSize = 2,
    line = FALSE,
    lineMethod = "lm",
    lineSE = TRUE,
    width = 500,
    height = 500,
    title = "",
    titleAlign = "center",
    titleFontSize = 16,
    subtitle = "",
    subtitleAlign = "left",
    subtitleFontSize = 16,
    caption = "",
    captionAlign = "right",
    captionFontSize = 12,
    xLabel = "",
    xLabelAlign = "center",
    xLabelFontSize = 16,
    yLabel = "",
    yLabelAlign = "center",
    yLabelFontSize = 16,
    titleType = "title",
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    yAxisRangeType = "auto",
    yAxisRangeMin,
    yAxisRangeMax,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0,
    xAxisRangeType = "auto",
    xAxisRangeMin,
    xAxisRangeMax,
    legendTitle = "",
    legendTitleFontSize = 16,
    legendLabelFontSize = 16,
    legendKeyWidth = 0.6,
    legendKeyHeight = 0.6,
    legenPositionType = "outside",
    legendPosition = "right",
    legendJustification = "center",
    legendPositionX = 0.8,
    legendPositionY = 0.5,
    legendDirection = "vertical") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("scat requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- scatOptions$new(
        x = x,
        y = y,
        group = group,
        flipAxes = flipAxes,
        pointSize = pointSize,
        line = line,
        lineMethod = lineMethod,
        lineSE = lineSE,
        width = width,
        height = height,
        title = title,
        titleAlign = titleAlign,
        titleFontSize = titleFontSize,
        subtitle = subtitle,
        subtitleAlign = subtitleAlign,
        subtitleFontSize = subtitleFontSize,
        caption = caption,
        captionAlign = captionAlign,
        captionFontSize = captionFontSize,
        xLabel = xLabel,
        xLabelAlign = xLabelAlign,
        xLabelFontSize = xLabelFontSize,
        yLabel = yLabel,
        yLabelAlign = yLabelAlign,
        yLabelFontSize = yLabelFontSize,
        titleType = titleType,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation,
        xAxisRangeType = xAxisRangeType,
        xAxisRangeMin = xAxisRangeMin,
        xAxisRangeMax = xAxisRangeMax,
        legendTitle = legendTitle,
        legendTitleFontSize = legendTitleFontSize,
        legendLabelFontSize = legendLabelFontSize,
        legendKeyWidth = legendKeyWidth,
        legendKeyHeight = legendKeyHeight,
        legenPositionType = legenPositionType,
        legendPosition = legendPosition,
        legendJustification = legendJustification,
        legendPositionX = legendPositionX,
        legendPositionY = legendPositionY,
        legendDirection = legendDirection)

    analysis <- scatClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

